# Generated by Django 4.2 on 2023-04-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0003_completionjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateai',
            name='body',
        ),
        migrations.RemoveField(
            model_name='templateai',
            name='variables',
        ),
        migrations.AddField(
            model_name='templateai',
            name='ai_example',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='templateai',
            name='human_example',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='templateai',
            name='prompt',
            field=models.TextField(help_text='This will be the body of the prompt, what the AI will receive to provide an answer', max_length=3499, null=True),
        ),
    ]
