# Generated by Django 4.2 on 2023-04-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_category_slug_alter_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemp',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
