# Generated by Django 4.2 on 2023-04-30 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_attemp_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attemp',
            new_name='Attempt',
        ),
    ]
